apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: ServiceAccount
      name: sample-service
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: sample-service@platform-ref-prod.iam.gserviceaccount.com
