apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: ServiceAccount
      name: sample-service
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          azure.workload.identity/use: "true"
      - op: add
        path: /metadata/annotations
        value:
          azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000"
