{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecret.targetKey }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey | quote }}
        property: EXAMPLE_CONFIG
{{- end }}
