apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-service
resources:
  - namespace.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - hpa.yaml
